### ISSUE TITLE
UTXO Model

### ISSUE THREAD

**Issue by TraceBundy** [FISCO-BCOS/FISCO-BCOS#106]
Why use the utxo model at dev branch, and what's the difference with qtum blockchain https://github.com/qtumproject/qtum

**Comment by chaychen2005** [comment]
1、Because of the release process, the code is merged into the dev branch and then into the master. The UTXO code has been submitted to the master.
2、According to the description of relevant materials, the design of qtum is based on the UTXO model with some new opcodes. FISCO BCOS implements the UTXO model based on the account model, and the related processes (such as data structures, the process of generating a block, etc.) are similar to ethereum. In this UTXO, we can implement user-defined functionality by passing in the contract address and calling parameters.

**Comment by bxq2011hust** [comment]
Long-time no reply, close issue. If there is any problem, please re-open at any time
