### ISSUE TITLE
搭建单群组4节点联盟链时候，提示nodes dir exists，please clean old dir。 如何解决

### ISSUE THREAD

**Issue by kukudekun** [FISCO-BCOS/FISCO-BCOS#2006]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rebel-ly** [comment]
cd nodes/127.0.0.1 
bash stop_all.sh
then you can rm -rf nodes , and using the build_chain.sh

**Comment by kukudekun** [comment]
> cd nodes/127.0.0.1 bash stop_all.sh then you can rm -rf nodes , and using the build_chain.sh

我照着这样做了，还是出现nodes dir exists，please clean old dir。 我想在服务器上搭建联盟链，是不是已经有人占用了端口才导致的这样的错误

**Comment by tannnn2022** [comment]
请问问题解决了吗？我也遇到了同样的问题

**Comment by rebel-ly** [comment]
您好，我是刘钰。您的邮件我已收到，我会尽快回复。谢谢！

**Comment by shenbaise24** [comment]
> > cd nodes/127.0.0.1 bash stop_all.sh然后您可以 rm -rf nodes ，并使用 build_chain.sh
> 
> 我照着这样做了，还是出现nodes dir exists，please clean old dir。我想在服务器上搭建联盟链，是不是已经有人占用了端口才导致的这样的错误

请问您的问题解决了吗，求回复

**Comment by rebel-ly** [comment]
没有得到解决 ---- 回复的原邮件 ***@***.***>发送日期2024年01月24日 16:10 ***@***.***> ***@***.***>***@***.***>主题Re: [FISCO-BCOS/FISCO-BCOS] 搭建单群组4节点联盟链时候，提示nodes dir exists，please clean old dir。 如何解决 (Issue #2006)


cd nodes/127.0.0.1 bash stop_all.sh然后您可以 rm -rf nodes ，并使用 build_chain.sh

我照着这样做了，还是出现nodes dir exists，please clean old dir。我想在服务器上搭建联盟链，是不是已经有人占用了端口才导致的这样的错误

请问您的问题解决了吗，求回复

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/FISCO-BCOS/FISCO-BCOS/issues/2006#issuecomment-1907604043",
"url": "https://github.com/FISCO-BCOS/FISCO-BCOS/issues/2006#issuecomment-1907604043",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
